version: 0.2.{build}

configuration: Release
test: off
build:
  project: src/Rooko.sln
  publish_nuget: true
  publish_nuget_symbols: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore src
after_build:
  - nuget pack src/Rooko.Core/Rooko.Core.csproj
  - nuget push Rooko.Core.{version}.nupkg -ApiKey OMxkQ6MQkv7dWbFGscKliMKO/xPWGbp5cUhOnC9WXQJ/joAOTStGKWT81/Kid0ky -Source https://www.nuget.org/api/v2/package