version: 0.11.{build}

configuration: Release
# test: off
build:
  project: src/Rooko.sln
  publish_nuget: true
  publish_nuget_symbols: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore src

deploy:
  - nuget push %APPVEYOR_BUILD_FOLDER%\*.dll -ApiKey %nuget_api_key% -Source https://www.nuget.org/api/v2/package