before_build:
  - nuget restore src
after_build:
  - nuget pack src/Rooko.Core/Rooko.Core.csproj
  - nuget setApiKey 558b8342-f274-48cd-b41e-5db35171df31 -Source https://www.nuget.org/api/v2/package
  - nuget push src/Rooko.Core/*.nupkg -Source https://www.nuget.org/api/v2/package